{% set version = "0.13.3" %}

package:
  name: pvcaptest
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/c/captest/captest-{{ version }}.tar.gz
  sha256: 9c47cf64d33a59dab2b57529d8ce85dae048351f9e422d51609025b525f08590

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python >=3.10
    - setuptools >=61
    - setuptools-scm >=8.0
    - wheel

  run:
    - python >=3.10
    - bokeh >=3
    - matplotlib-base >=2
    - numpy >=1.24.4,<2.4
    - pandas >=1,<3
    - python-dateutil >=2.5
    - scikit-learn >=0.19
    - statsmodels >=0.8
    - holoviews >=1.14.8
    - pvlib-python >=0.9
    - param <2.0
    - colorcet
    - openpyxl
    - panel

test:
  imports:
    - captest
  requires:
    - pip
  commands:
    - pip check

about:
  home: http://github.com/pvcaptest/pvcaptest
  license: MIT
  license_file: ./LICENSE.txt
  summary: Framework and methods to facilitate photovoltaic facility capacity testing following ASTM E2848.
  doc_url: https://pvcaptest.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - bt-
