{% set version = "0.11.0" %}

package:
  name: pvcaptest
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/c/captest/captest-{{ version }}.tar.gz
  sha256: fdc6dd17048125370a24075b5a6bdd5f5486297ec6a01f4ef1e1f544acdcd54a

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python >=3.7

  run:
    - bokeh >=1
    - matplotlib-base >=2
    - numpy >=1.13.0
    - pandas >=1
    - python >=3.7
    - python-dateutil >=2.5
    - scikit-learn >=0.19
    - statsmodels >=0.8
    - holoviews >=1.11
    - pvlib-python >=0.7

test:
  imports:
    - captest
  requires:
    - pip
  commands:
    - pip check

about:
  home: http://github.com/pvcaptest/pvcaptest
  license: MIT
  license_file: ./LICENSE.txt
  summary: Framework and methods to facilitate photovoltaic facility capacity testing following ASTM E2848.
  doc_url: https://pvcaptest.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - bt-
